### ISSUE TITLE
Sorry, I want to ask another problem about reaper

### ISSUE THREAD

**Issue by gemengtju** [evictor/html5-canvas-gradient-creator#4]
Dear Sir,
sorry, I don't have your email, so I just ask a problem about REAPER problem. I found you have solved this problem using ffmpeg command line. The problem was described on the address https://github.com/google/REAPER/issues/14

However, I have tried to use ffmpeg command line to convert our audio file as follow:

<img width="893" alt="image" src="https://user-images.githubusercontent.com/53182650/64109416-0ac3fd00-cdb2-11e9-8677-06a3d220c6dd.png">

and then used the reaper command line again, but the code didn't work again.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/53182650/64109474-37781480-cdb2-11e9-916d-4236aa2dd4d3.png">

So, could you help me to deal with the problem?
The wav I used is upload on: https://pan.baidu.com/s/1CqL-q761FLJeSuelLoTHow
and the link password is: zesd

**Comment by evictor** [comment]
Closing... replied in the REAPER thread
